name: Using Secrets

on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    - name: Use secret
      env:
        SECRET_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
      run: |
        echo "Token length: ${#SECRET_TOKEN}"
        echo "First 3 chars: ${SECRET_TOKEN:0:3}***"
        # ⚠️ never display secret token